### ISSUE TITLE
Manual pagination

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-business-sdk#203]
Is there a way to manually paginate responses with this library? As in, call functions in a way that only one request is made but a handler is exposed like (`response.next_page()`) to fetch the next page of results? This is often preferred to automatic pagination when implementing rate limits in a wrapper and whatnot

**Comment by rituparnamukherjee** [comment]
Not currently supported, You can have this customization from your end.

**Comment by tejasmanohar** [comment]
Gotcha. This would be a really great feature because it's nearly impossible to implement proper rate limiting without it (unless you use dependency injection to decorate internal Cursor/iteration functions). Would you be open to PRs?

**Comment by rituparnamukherjee** [comment]
Sure, I think we can incorporate this as a PR :)

**Comment by tejasmanohar** [comment]
Cool, will do. Maybe keep the issue open to track status?

**Comment by rituparnamukherjee** [comment]
Sure.

**Comment by tejasmanohar** [comment]
I think a generator approach to all endpoints is ideal for any endpoints that auto-paginate. The current approach of auto-paginating and holding all objects in memory can cause OOMs.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for quite a while now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
