### ISSUE TITLE
Batch fetching is not return data.

### ISSUE THREAD

**Issue by ledinhbao** [facebook/facebook-python-business-sdk#206]
Dear all,

I want to perform a batch request with around 20 AdsInsight data for my campaigns. So this is the code for add the request to batch:

```
infields = [AdsInsights.Field.website_ctr, AdsInsights.Field.reach, AdsInsights.Field.spend, AdsInsights.Field.clicks]
params = { 'date_preset': AdsInsights.DatePreset.today }
thebatch = FacebookAdsApi.get_default_api().new_batch()
```

// Assume that I have 20 campaigns, so I add the requests to batch.
`active_account.get_campaigns()[0].get_insights(fields = infields, params = params, batch = thebatch)`

// Then call the API
`thebatch.execute()`
# 

So it seems like API has provide no way to retrieve the data from those batch requests. I looked at the source code and discovery that via AdsObject classes, it cannot be passed the success & failure callback to the batch.

Does anyone here get the same trouble?

Campaign's get_insights def in API source file:
`def get_insights(self, fields=None, params=None, async=False, batch=None, pending=False)`

**Comment by zhe1ka** [comment]
Hi, there
it is already an old question but may be it helps somebody

I have a little different example (working example), but very similar for it

`    batch_data = [
        {
            'method': "GET",
            'relative_url': "v2.8/act_668439229891890/reachestimate?currency=USD&optimize_for=OFFSITE_CONVERSIONS&targeting_spec={'geo_locations': {'location_types': ['recent', 'home'], 'countries': ['US']}}",
        }
    ]
    batch_result = []

    def callback(data):
        batch_result.append(data.json()['data']['users'])

    api_batch = api.new_batch()

    for item in batch_data:
        api_batch.add(
            method=item['method'],
            success=callback,
            relative_path=item['relative_url']
        )

    api_batch.execute()`

have a good day!)

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
