### ISSUE TITLE
Typechecker support for custom classes

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-business-sdk#221]
Hi there,

This [line](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/typechecker.py#L210-L216) in the `TypeChecker` class makes it impossible to define custom classes. For instance if I wanted to have a custom class of `AdLabel`, then the `Ad.adlabels` field would still be a list of standard `AdLabel` objects instead of my custom class. It would be a one liner to support that. Would you accept a pull request?

Thanks.

**Comment by olasfar** [comment]
+1

**Comment by rituparnamukherjee** [comment]
@m-vdb 

Yep, we can take a look into a PR for this. Go ahead and send one :)

**Comment by m-vdb** [comment]
@rituparnamukherjee see #232

**Comment by m-vdb** [comment]
@rituparnamukherjee come on it's not that complicated to hit the merge button

**Comment by rituparnamukherjee** [comment]
@JiamingFB, leaving it up to you guys to take a call and merge.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
