### ISSUE TITLE
Business Class doesn't have get_endpoint method

### ISSUE THREAD

**Issue by lucasrcosta** [facebook/facebook-python-business-sdk#230]
The Business doesn't have a `get_endpoint` method, useful for getting a User`s Businesses for example.

``` python
class Business(Business):

    @classmethod
    def get_endpoint(cls):
        return 'businesses'
```

**Comment by rituparnamukherjee** [comment]
@lucascosta ,

Thanks for bringing this up.
The business manager related API is internally not migrated into the graph framework we are relying on for autogen. Once it is migrated we should have this incorporated automatically.

For now we will patch a helper method to do this soon.

**Comment by lucascosta** [comment]
Thank you. Patching it myself here too...

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
