### ISSUE TITLE
TypeChecker and Ad objects

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-business-sdk#233]
Hi there,

I think that the `TypeChecker`class is a good idea but I'm confused about its usage. For instance, it's used properly in the [`AbstractObject`](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/abstractobject.py#L54), i.e. it verifies the object types based on what's defined on the class, but it's not used properly (IMHO) when creating / updating objects, for instance for the `Ad` object [here](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/ad.py#L194-L215).

I suggest we (i.e. your autogeneration mecanism) defines class attributes that are accessible and easily override-able. Otherwise it makes the whole API pretty difficult to understand (for instance, I was wondering what was the `_field_types` attributes, then I guessed that it was used to check the consistency of the field types, then I got disappointed to see that it wasn't used for API methods...)

cc @rituparnamukherjee 
(this relates to #221 and #232)

**Comment by rituparnamukherjee** [comment]
cc @JiamingFB , Jiaming you might be in a better position to discuss on this.

**Comment by misbahul07** [comment]
As'salamualaikum wr wb...

**Comment by m-vdb** [comment]
any news on that matter?

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
