### ISSUE TITLE
Expose Raw HTTP Response

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-business-sdk#243]
This is often nice for collecting metrics and whatnot. Would you be opposed to supporting something like [requests-middleware](https://pypi.python.org/pypi/requests-middleware/0.1.0) or exposing this as a property on the returned objects. If so, I'd be down to PR something.

**Comment by shivekkhurana** [comment]
This will also help read the decay factor, and current decay status, on rate limited accounts (facing this problem while fetching insights).

**Comment by guxuoss** [comment]
Thanks for reporting the issue.  We already received the new feature request.  We cannot commit when this feature will be available.  And at the meantime, you are more than welcome to ask for a pull request.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
