### ISSUE TITLE
publisher_platform and platform_position not valid but still in AdsInsights Field class

### ISSUE THREAD

**Issue by Alonreznik** [facebook/facebook-python-business-sdk#245]
Hey all.
I want to get all of the available fields in AdsInsight report, so i can send a request with them. Therefore, i get them all with 
`fields = AdsInsights.Field.__dict__.values()`

The Field class contains some fields that became not valid in the current version (2.7.1): publisher_platform and publisher_position.

The response i get when i send them in the fields is: 

> publisher_platform,  platform_position are not valid for fields param. All valid values are: date_start, date_stop, account_id, account_name, ad_id, ad_name, buying_type, campaign_id, campaign_name, adset_id, adset_name, objective, actions, unique_actions, total_actions, total_unique_actions, action_values, total_action_value, impressions, social_impressions, clicks, social_clicks, unique_impressions, unique_social_impressions, unique_clicks, unique_social_clicks, spend, frequency, social_spend, deeplink_clicks, app_store_clicks, website_clicks, cost_per_inline_post_engagement, inline_link_clicks, cost_per_inline_link_click, inline_post_engagement, unique_inline_link_clicks, cost_per_unique_inline_link_click, inline_link_click_ctr, unique_inline_link_click_ctr, call_to_action_clicks, newsfeed_avg_position, newsfeed_impressions, newsfeed_clicks, reach, social_reach, ctr, unique_ctr, unique_link_clicks_ctr, cpc, cpm, cpp, cost_per_total_action, cost_per_action_type, cost_per_unique_click, cost_per_10_sec_video_view, cost_per_unique_action_type, objective_results, optimization_results, relevance_score, website_ctr, video_avg_sec_watched_actions, video_avg_pct_watched_actions, video_p25_watched_actions, video_p50_watched_actions, video_p75_watched_actions, video_p95_watched_actions, video_p100_watched_actions, video_complete_watched_actions, video_10_sec_watched_actions, video_15_sec_watched_actions, video_30_sec_watched_actions, estimated_ad_recallers, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound, estimated_ad_recall_rate, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, cost_per_estimated_ad_recallers, canvas_avg_view_time, canvas_avg_view_percent, place_page_name, ad_bid_type, ad_bid_value, ad_delivery, adset_bid_type, adset_bid_value, adset_budget_type, adset_budget_value, adset_delivery, adset_start, adset_end

Please remove them from the class.

Thanks!

**Comment by guxuoss** [comment]
Thanks for reporting this bug.  It is caused by an internal setup that aims to support a legacy feature in old manual SDKs.  We will clean them in later releases.

**Comment by ohlaylaohoh** [comment]
I noticed that as well. However I still want to get the publisher_platform breakdown. What do I do?

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
