### ISSUE TITLE
Add act_ prefix explanation in README

### ISSUE THREAD

**Issue by mcmonster** [facebook/facebook-python-business-sdk#295]
I dipped my toe into the Facebook Ads API tonight, and enduring a fair amount of forehead-to-desk collisions thanks to the 'act_' prefix in the account ID. Is the need to add this prefix when directly retrieving an AdAccount explained in the README?

It's late (EST) so it's perfectly possible I am just being dense. If it's not just me, please comment to that effect and I'll submit a PR.

**Comment by cloudxu** [comment]
Thanks @mcmonster for reporting this issue. I agree we shall improve the developer experience for this API. Actually our SDK in other language (like Java) already does for new AdAccount(long). We will fix this for python

**Comment by diek** [comment]
I encountered the same issue, and I am not understanding why there is a need to do this. The account id is numeric, at least mine is. It is not intuitive

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
