### ISSUE TITLE
get_custom_conversions at AdAccount level

### ISSUE THREAD

**Issue by pita2k** [facebook/facebook-python-business-sdk#328]
Hi, I think it would be nice if we implement get_custom_conversions at the AdAccount level,

It seems weird that there is a create custom conversion endpoint but not a getter, (for all custom conversions in the ad accont level)

**Comment by abetomo** [comment]
I also want to use get_custom_conversions, but do you have any additional plans?

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
