### ISSUE TITLE
Application Object

### ISSUE THREAD

**Issue by pita2k** [facebook/facebook-python-business-sdk#329]
Hi,

I think it would be nice if we implemented an application.py adobject,
(for facebook app / canvas app / android ios )

there are a lot of calls being made to that node type
i.e: 'object_store_urls'

Thanks

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
