### ISSUE TITLE
Business object doesn't have method to claiming pages

### ISSUE THREAD

**Issue by vova-ukraine** [facebook/facebook-python-business-sdk#330]
Business object (adobjects/business)  doesn't have method to claiming pages according to documentation: https://developers.facebook.com/docs/marketing-api/businessmanager/assets#pages

```
curl \
-F "page_id=<PAGE_ID>" \
-F "access_type=OWNER" \
-F "access_token=<ACCESS_TOKEN>" \
"https://graph.facebook.com/<API_VERSION>/<BUSINESS_ID>/pages"
```

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
