### ISSUE TITLE
No module name 'facebookads.objects'

### ISSUE THREAD

**Issue by david-mag** [facebook/facebook-python-business-sdk#331]
```
In [6]: from facebookads.objects import AdAccount, Insights
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-10fdae17b419> in <module>()
----> 1 from facebookads.objects import AdAccount, Insights

ImportError: No module named 'facebookads.objects'
```

Version 2.9.1 does not let me import module facebookads.objects.

**Comment by DannyLee12** [comment]
Having the same Issue, +1

**Comment by DannyLee12** [comment]
```
Traceback (most recent call last):
  File "examples/read_objects.py", line 27, in <module>
    from facebookads.objects import (
ModuleNotFoundError: No module named 'facebookads.objects'
```

**Comment by anupmandvariya** [comment]
I am also facing this issue from yesterday.

**Comment by anupmandvariya** [comment]
Got it sorted. The issue is object is deprecated and one has to use adobject.

**Comment by pita2k** [comment]
It was exposed in the previous version as a deprecated module,
but it seems now that they decided to remove it,

use
from facebookads.adobjects import <OBJECT>

**Comment by david-mag** [comment]
It's still used in the sample code though ... and the README.

**Comment by ProsperousHeart** [comment]
This is an easy fix ... Can someone please update?

**Comment by boxbeatsy** [comment]
When will the README and examples/ documentation be updated to reflect the most recent changes with the objects module?  As a new dev, I'm wondering if I should work off an old package version so I can get started quickly. Thanks.

**Comment by mikeengland** [comment]
+1

**Comment by john-galvagno** [comment]
Does anyone have any sample code they can throw my way?  I am not a super experienced coder and usually build my code off of other examples.  This would be hugely helpful for me!

Thanks!

**Comment by john-galvagno** [comment]
honestly any sample code at all would be great, doesn't have to be very abstract!  I am just running into issues even getting off the ground unfortunately :/

**Comment by mikeengland** [comment]
@john-galvagno I think you just need to do

'from facebookads.adobjects import AdAccount' or whatever object you need

**Comment by john-galvagno** [comment]
@mikeengland I appreciate the suggestion...I was actually able to figure it out a bit.

To anyone else reading this, take a look at this for a working example: https://github.com/DrDeathBubbles/Facebook-Ads-AJM/blob/master/Ads_tools.py

Also note, that Facebook provides some python examples on their docs.  You can find those here: https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group/ (just hit the button "Ads API Python SDK" next to the examples.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
