### ISSUE TITLE
pip install facebookads issue

### ISSUE THREAD

**Issue by pita2k** [facebook/facebook-python-business-sdk#336]
Hi,

getting the package using pip install facebookads==2.9.1 installs old files,

specs.py still contains 
"from facebookads.objects import AdPromotedObject"

**Comment by leoht** [comment]
Hi,
we have the same issue, `facebookads.adobjects.adaccountuser` still imports the module `facebookads.adobjects.adaccountgroup`, which doesn't seem to exists.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues. We're looking into this...Thanks!

**Comment by Federico-Comesana** [comment]
Guys. I'm facing the same problem.
Issue  #310 was resolved and merged into master but when I download facebookads using PIP y get version 2.9.1 and it still have the wrong import 'from facebookads.objects import AbstractObject' even when in master is 'from facebookads.adobjects.abstractobject  import AbstractObject'

@daphyFB  do I missing something?

**Comment by uppercasebrands** [comment]
@Federico-Comesana @leoht @pita2k In order to get Facebook Python SDK working, you should pip install --upgrade using the github repo. The current pip version is broken. Try: pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git

**Comment by Federico-Comesana** [comment]
Thanks @uppercasebrands .
Do you have an ETA of when Pypi will be updated?

**Comment by uppercasebrands** [comment]
@Federico-Comesana That is a question suitable for @daphyFB or @JiamingFB. I don't work at FB, but am just volunteering to help for making the SDK better for everyone :)

**Comment by tommyboy326** [comment]
Thanks @uppercasebrands .
pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git 
it work for me thanks you so much

**Comment by codytwinton** [comment]
This issue appears to have been resolved in our latest version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
