### ISSUE TITLE
Video Upload Error

### ISSUE THREAD

**Issue by diego-pedroza** [facebook/facebook-python-business-sdk#344]
When upload an AdVideo always throws this error:

error_subcode: 1363030
error_user_msg: Your video upload timed out before it could be completed. This is probably because of a slow network connection or because the video you're trying to upload is too large. Please try again.

Used code
`video = AdVideo(parent_id="####")

    video_path = os.path.join(
        os.path.dirname(__file__),
        os.pardir,
        'web/static/assets/video.mp4'
    )

    # set video fields
    video[AdVideo.Field.filepath] = video_path

    # remote create
    video.remote_create()
    video.waitUntilEncodingReady()`

Also this error is not handled, have to set a breakpoint at video_uploader.py Line 206 to notice error.

**Comment by cloudxu** [comment]
@diego-pedroza, Thank you for reporting issue to us. Your feedback is important to us.

Trying to understand more about your problem.

What you see is an API exception our server responded. And we can't really do much about it. For the SDK side, I see the error is handled: https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/video_uploader.py#L228-L251

Are you saying it didn't get to "raise e" line in the code? Or you want us to handle the exception? We think we shall keep SDK assertive without handle API exception. Your application code should make the decision on whether or not to handle it and whether or not to retry it.

**Comment by diego-pedroza** [comment]
Actually I said that error is not handled because code remains in while and make several requests to Facebook and then Facebook API reach requests limit. I search for this code error and there's no much info but at some blogs says that request is missing Content-Type

http://stackoverflow.com/questions/30922016/getting-error-subcode-1363030-when-trying-to-upload-a-video-chunk

SDK code for this is not complex and I'm actually working with your example  code (examples/upload_video.py) but this throws inmediately that error, by the way if I use Postman request works perfectly.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
