### ISSUE TITLE
Not  able to retrieve ad URL, getting error of invalid field. 

### ISSUE THREAD

**Issue by dhanrajvr** [facebook/facebook-python-business-sdk#351]

**Comment by uppercasebrands** [comment]
@dhanrajvr Can you please add some more information? Can you add (copy/paste) the call you are issuing and the error response output you are getting? Commandline text or screenshot would do.

**Comment by dhanrajvr** [comment]
@uppercasebrands  Hi, the problem adinsights() doesn't have a field 'url'. can you tell me which function to use so that i can retrieve ad URL? 
![screenshot from 2017-06-01 11-53-43](https://cloud.githubusercontent.com/assets/24914862/26667139/50a696d6-46c1-11e7-9709-cdce460186ca.png)

**Comment by anupmandvariya** [comment]
I am facing the same issue where I want to extract Website URL information from AdCreative Class with Field as link_url. However, I am not getting any value for the same.

**Comment by rorynelsonscott** [comment]
@dhanrajvr the insights API isn't super robust, for many attributes you may want to match with metrics, you'll have to make multiple calls and put them together yourself. To match the data with the insights api, we have to pull an Ad-level report, then an AccountAds call to get CreativeID, then get AccountAdCreates to finally match the creative to the ad to the ad insights.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
