### ISSUE TITLE
reachestimation missing bid_estimations

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-python-business-sdk#365]
I follow examples https://developers.facebook.com/docs/marketing-api/reference/ad-account/reachestimate/ 

and found the response only have
`[<ReachEstimate> {
    "estimate_ready": true,
    "users": 125000000
}]`

So can someone take a look about the issue.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
