### ISSUE TITLE
line 606 needs an additional condition of target_class!=AbstractCrudObject

### ISSUE THREAD

**Issue by zwales** [facebook/facebook-python-business-sdk#366]
I'm currently working with lines 603-608 in api.py, and was trying to understand why I was getting so many warnings on my call when specifying fields. In this case, I'm trying to hit the /advertisable_applications endpoint, which is an AbstractCrudObject, which no fields are ever specifically linked. 

To fix this, could line 606 have an additional condition of target_class!=AbstractCrudObject

The warnings tend to spawn zombie processes which over time make my application unusable.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
