### ISSUE TITLE
Leads impossible to download entirely

### ISSUE THREAD

**Issue by axelgrowth** [facebook/facebook-python-business-sdk#374]
Hi there, 

I have been using the Bulk read to catch leads from a given form ID. Code is below and is pretty straight forward, just copy paste from the documentation. 

```def retrieve_leads(form_id):
        '''
        INPUT: bigInt
        OUTPUT: iterable
        DESCRIPTION: retrieve the leads of a given form_id
        '''

        form = LeadgenForm(form_id)
        leads = form.get_leads()
        return leads
```
However, the leads object returned by this code below only contain 25 leads and unlike what is said in the documentation, *it does not contain the paging data. *

Any guess what's going on?

Thanks

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
