### ISSUE TITLE
Example code is not updated to match API

### ISSUE THREAD

**Issue by ckinsey** [facebook/facebook-python-business-sdk#378]
Sample code in the repository is still referencing importing most Ad objects via the `facebookads.objects` module, which appears to have been removed in version 2.8.  Thus running sample code from this repository results in `ImportError`.

There also does not appear to be a singular place to import these objects, so we had to dig through each module in order to find and import the objects from where they are declared.

**Comment by david-mag** [comment]
https://github.com/facebook/facebook-python-ads-sdk/issues/331

**Comment by codytwinton** [comment]
This appears to be a duplicate of #331. Closing.
