### ISSUE TITLE
Cannot create AdVideo via AdAccount

### ISSUE THREAD

**Issue by Odelya** [facebook/facebook-python-business-sdk#379]
FB supports 2 different ways of creating ad videos:

https://developers.facebook.com/docs/marketing-api/reference/ad-account/advideos

and 

https://developers.facebook.com/docs/marketing-api/advideo/v2.9

However, the parameters to create an ad video is different between the 2 calls - 

the second approach, to create AdVideo while setting the parent_id to the ad account accepts filepath, while the other method of creating AdVideo as part of the an AdAccount accepts file_url.

FB SDK deprecated the second option (of creating a directly AdVideo), however, I don't find an equivalent method in AdAccount -> create ad video that allows uploading from file path.

See AdVideo:

https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/advideo.py

See the way to create it via AdAccount:
https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adaccount.py

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
