### ISSUE TITLE
Leadgen.get_leads() not supporting filtering

### ISSUE THREAD

**Issue by eviatarkhen** [facebook/facebook-python-business-sdk#381]
Looks like the PHP sdk and curl allows filtering by time, however it seems that this feature is missing in the python SDK.
Is it expected to be added soon? If not, I would patch the code (and I prefer not to :))

**Comment by axelrelayrides** [comment]
@eviatarkhen if you end up patching it please let us know ! The python SDK is far behind on the lead  front!

**Comment by kaliaabhishek** [comment]
Can I pass the "LEAD_GEN" objective type as a string though? There is no object for it.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
