### ISSUE TITLE
Getting HTTP response headers on get_insights call

### ISSUE THREAD

**Issue by jsangilve** [facebook/facebook-python-business-sdk#382]
Is there any way to access the HTTP Response header `X-FB-Ads-Insights-Throttle` after calling the `get_insights` method from Campaign object.

Thanks

**Comment by ultraN** [comment]
Assume response = your insights call.
response.headers() gives you all headers in response, and so you can find throttle info.

**Comment by MeghanaMunj** [comment]
Hello Not able to find the  X-FB-Ads-Insights-Throttle in the response.headers
getting the following
response header is ---------*****
-----[{u'name': u'Access-Control-Allow-Origin', u'value': u'*'}, {u'name': u'Vary', u'value': u'Accept-Encoding'}, {u'name': u'Pragma', u'value': u'no-cache'}, {u'name': u'Strict-Transport-Security', u'value': u'max-age=15552000; preload'}, {u'name': u'ETag', u'value': u'"1050253afa81406eee"'}, {u'name': u'Expires', u'value': u'Sat, 01 Jan 2000 00:00:00 GMT'}, {u'name': u'Content-Type', u'value': u'text/javascript; charset=UTF-8'}, {u'name': u'Facebook-API-Version', u'value': u'v2.10'}, {u'name': u'Cache-Control', u'value': u'private, no-cache, no-store, must-revalidate'}]

**Comment by AlexAslan** [comment]
@ultraN Could you provide an example on how to get the headers. How I could get the headers here

async_job = account.get_insights(params=params['query'], async=True)
async_job.remote_read()

while async_job[AdReportRun.Field.async_percent_completion] < 100:
    time.sleep(1)
    async_job.remote_read()

result = async_job.get_result(params={"limit": 500})

**Comment by staubda** [comment]
Any update on this issue? @ultraN's suggestion doesn't work as insights calls, or any GET request to an edge (as you can see from looking at the [execute](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/api.py#L652) method of the `FacebookRequest` object), return a `Cursor`.

The only hacky python solution I've found is to do something like:
```
subprocess.check_output([
    'curl', 
    '-IXGET',  # get only response header
    '-G', 
    '-d', 'fields=impressions,clicks', 
    '-d', 'breakdowns=gender', 
    '-d', 'access_token={}'.format(os.environ['FB_TOKEN']), 
    '-d', 'appsecret_proof={}'.format(FacebookSession(app_secret=os.environ['FB_APP_SECRET'], access_token=os.environ['FB_TOKEN']).requests.params['appsecret_proof']),
    '-d', 'time_range={"since":"2015-03-01","until":"2018-03-31"}',
    'https://graph.facebook.com/v2.11/123456789/insights'
])
```

**Comment by codytwinton** [comment]
This feature request doesn't appear to be actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
