### ISSUE TITLE
Campaign effective_status

### ISSUE THREAD

**Issue by mensurm** [facebook/facebook-python-business-sdk#388]
On the campaign level the class EffectiveStatus contains all the possible statuses. 
Also the get_campaigns method of AdAccount class, specifies this object as one of the possible filters that can be set. 
However, when trying to obtain all campaigns regardless of their effective status I get this error response saying the specified Run Status is invalid, event though the status specified belongs to the EffectiveStatus class. The equivalent request for ads and ad sets works fine, it is only on the campaign level that this issues appears. 

```
response:
    {
      "error": {
        "code": 100, 
        "is_transient": false, 
        "error_subcode": 1487561, 
        "error_user_msg": "Only certain values may be specified for run status.  The value specified was invalid.", 
        "error_user_title": "Run Status not valid", 
        "message": "Invalid parameter", 
        "type": "OAuthException", 
        "fbtrace_id": "B+WfJKeHB8o"
      }
    }
```

This is the call 
```

ad_account = AdAccount(fbid=account.id)
params = {
            'effective_status': [Campaign.EffectiveStatus.active, Campaign.EffectiveStatus.campaign_paused,
                                 Campaign.EffectiveStatus.paused, Campaign.EffectiveStatus.archived,
                                 Campaign.EffectiveStatus.disapproved, Campaign.EffectiveStatus.preapproved,
                                 Campaign.EffectiveStatus.pending_billing_info, Campaign.EffectiveStatus.pending_review]

        }

campaigns = ad_account.get_campaigns(fields=[Campaign.Field.id, Campaign.Field.name, Campaign.Field.effective_status], params=params)
```

**Comment by onmolecule** [comment]
Just had same issue, I know this is an old thread but figured I'd leave this here. Seems this endpoint only works with these flags: ["ACTIVE", "PAUSED","ARCHIVED"].

Super lame.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
