### ISSUE TITLE
Zero impression stats in reports

### ISSUE THREAD

**Issue by sfontana** [facebook/facebook-python-business-sdk#391]
I'm having trouble getting zero stats reports.

For instance if I want to get stats for a campaign that exists but that for some reason has 0 impressions (e.g. no budget): v2.10/act_xxxx/insights?fields=impressions&filtering=[{'field':'campaign.name','operator':'CONTAIN', 'value':'NO_BUDGET_CAMPAIGN'}]

I would expect to get" { "data": [ { "impressions": "0" } ] }

but the call returns: { "data": [ ] }

Zero impressions are very useful for discovering entity structures. Also these are shown in the power editor.

Is there a way to get the 0 impression reports using the API? Otherwise I'll have to fill the missing entries by myself but it can get quite complex, specially if breakdowns are being used.

Cheers

Repro URL:
https://developers.facebook.com/tools/explorer/826197540765315/?session_id=1645353818809592

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by sfontana** [comment]
The issue persists: https://developers.facebook.com/tools/explorer/826197540765315/?session_id=295335774396294


Also related:
If I request `outbound_clicks` how am I supposed to know that there might be a `submetric`called `outbound_click` if it's only returned for non-zero impressions?
It's not even listed here https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/#Overview and it's no where to be found in the library.

This is a problem because I cannot differentiate between metrics that don't exist and metrics that are not returned because they have 0 value.
