### ISSUE TITLE
AdImageMixin.remote_read doesn't use the right API 

### ISSUE THREAD

**Issue by dmk23** [facebook/facebook-python-business-sdk#392]
In our application, we never set the global/default FacebookAdsApi to avoid concurrency errors. Instead we rely explicitly on managing our own API objects in a thread-safe way.

We've run into the issue of `AdImage.remote_read` always failing. Tracking down the problem we found the root cause in `AdImageMixin.remote_read` that instantiates AdAccount using global API and ignoring the true API passed with the original AdImage object:
https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/helpers/adimagemixin.py#L154

Our hack solution was to monkey-patch `AdImage.remote_read` by cloning it and adding a line `account._api = self._api`. However we'd like to report the problem and suggest a stronger support / automated testing for use cases with no global/default API set

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
