### ISSUE TITLE
[Post performance data]How to get get post_id associated with an ad from FB Marketing API

### ISSUE THREAD

**Issue by ssundara-nw** [facebook/facebook-python-business-sdk#393]
We launched bunch of social campaigns recently and working on building a social dashboard which has ad/adset level spend data <-> with post level metrics.

While fetching post performance data thru API we ran into these two issues and need some help or direction with.

1. We use Graph API to get all posts for our NW page and then iterate over posts to get post level social metrics like - likes,shares etc

# Add date range to params
    params['since'] = start_date
    params['until'] = end_date

    # Overwrite fields
    params['fields'] = ['id']
    params['limit'] = 100

    ids = []
    raw_data, next_url = graph_api.request(end_points=[CONFIG["page_id"],"posts"], params=params, paginate=None)

post_params = {'fields':','.join(["id","shares","status_type"]), 'period':'lifetime'}
graph_api.request(end_points=[<business id>,"posts"], params=params, paginate=None)

[Question] - This ONLY provides published posts but not Advert Posts. How can we get social performance data for Advert Posts ?

https://business.facebook.com/ads/manage/powereditor/pages?section=ADS_POSTS&sort[0]=edited_by_descending

Inline image 1

2. We use FB Marketing API SDK to fetch ad performance data at ad and adset level. how can we identify the post id, permalink associated with ad id ? 

currently we are using the "AdCreative" class to fetch object_story_id and then use that data to tag to ad level data. this is working for published posts but In case of ads with advert posts object_story_id comes as NULL.

https://developers.facebook.com/docs/marketing-api/reference/sdks/python/ad-creative/v2.10

what is the recommended way to get post_id for an ad ? In the API Ad object doesnt have anything to related to post.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
