### ISSUE TITLE
Ad object `tracking_specs` type validation value is wrong. `Object` must be `list<Object>` Incorrect Warnings generated

### ISSUE THREAD

**Issue by dvdotsenko** [facebook/facebook-python-business-sdk#395]
While `Ad._field_types['tracking_specs']` is correctly set to `'list<ConversionActionQuery>'`,  `Ad.api_update`'s `param_types` incorrectly sets `"tracking_specs" to `"Object"`. It should probably be `'list<Object>'`

https://github.com/facebook/facebook-python-ads-sdk/blob/c0704f53f1e0c3127a2ec741b83e2739000d7a88/facebookads/adobjects/ad.py#L212

Current setting incorrectly generates unsightly warnings that spill out to our ads publication control console. Please update.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
