### ISSUE TITLE
Setup process doesn't work for python3

### ISSUE THREAD

**Issue by geoffwalmsley** [facebook/facebook-python-business-sdk#398]
The sample code to test the marketing api is setup breaks on python3. Bad print statements... obviously easy to fix

Also, when run, the sample code code gives an error:

"message": "(#2663) Terms of service has not been accepted. To accept, go to https://www.facebook.com/customaudiences/app/tos/?act=1234..

But the link is to an expired page.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
