### ISSUE TITLE
Video API Error

### ISSUE THREAD

**Issue by diegopedroza** [facebook/facebook-python-business-sdk#399]
Hi, I'm trying to upload a video via python sdk but always send this error 'Your video upload timed out before it could be completed. This is probably because of a slow network connection or because the video youre trying to upload is too large. Please try again.' (Error caught on video_uploader.py line 229) 
Tried with a video of less than 1Mb and also for one of 7MB and also my connection is ok. I posted this issue months ago but without response until now. This is one of videos used
http://52.207.122.11/video.mp4
Code is really simple:
    
    import os
    
    from facebookads import FacebookAdsApi
    from facebookads import FacebookSession
    from facebookads.adobjects.advideo import AdVideo
    
    import lib.config as config
    
    session = FacebookSession(
        config.FACEBOOK_APP_ID,
        config.FACEBOOK_APP_SECRET,
        config.FACEBOOK_ADMIN_TOKEN
    )
    
    FacebookAdsApi.set_default_api(FacebookAdsApi(session))
    
    if __name__ == "__main__":
        video = AdVideo(parent_id=config.FACEBOOK_TESTING_AD_ACCOUNT_ID)
    
        video_path = os.path.join(
            os.path.dirname(__file__),
            os.pardir,
            "web/static/assets/video.mp4"
        )
    
        video[AdVideo.Field.filepath] = video_path
        video.remote_create()
        video.waitUntilEncodingReady()
        print(video)

Using lib version 2.10.1
Note: Facebook Accelerator Team told me to create a new issue to accelerate this fix

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
