### ISSUE TITLE
Saved Audiences support missing

### ISSUE THREAD

**Issue by jonathon-oodar** [facebook/facebook-python-business-sdk#404]
I've noticed that there doesn't seem to be any support for Saved Audiences in this sdk yet. Is this something that's on the horizon?

Additionally would anyone know of a workaround to fetch the data with this sdk in the meantime, or is my only option to use direct Open Graph calls?

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
