### ISSUE TITLE
Upload offline event data

### ISSUE THREAD

**Issue by joaofranca** [facebook/facebook-python-business-sdk#408]
Is it possible to [upload offline events](https://developers.facebook.com/docs/marketing-api/offline-conversions) using this sdk?

**Comment by fai-huntrakool** [comment]
You can try using this:

def update_offline_conversion_data_set(nodeid,params):
    request=FacebookRequest(
            method='POST',
            node_id=nodeid, #Offline event ID
            endpoint='/events',
            target_class=AbstractCrudObject,
            api_type='NODE'   
            )
    request.add_params(params)
    request.execute()

while nodeid and params are
nodeid= your offline dataset id
params={'data':data,'upload_tag':'store_date'}

**Comment by joaofranca** [comment]
@fai-huntrakool thank you, that works nicely :D

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
