### ISSUE TITLE
v2.10.1 OAuthException Exception in exceptions.py

### ISSUE THREAD

**Issue by joeybloggs** [facebook/facebook-python-business-sdk#409]
There is an issue in [exceptions.py](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/exceptions.py#L80) when trying to retrieve users `user.get_ad_accounts()`
```python
if self._error.get('error_data', {}).get('blame_field_specs'):
                self._api_blame_field_specs = \
                    self._error['error_data']['blame_field_specs']
```

`self._error` contains `{'error_subcode': 490, 'code': 190, 'fbtrace_id': 'G0VnrxUSf3t', 'message': 'Error validating access token: The user is enrolled in a blocking, logged-in checkpoint', 'type': 'OAuthException', 'error_data': '{"checkpoint_flow_id":"1501092823525282","checkpoint_content_id":"0"}'}`

as you can see `error_data` is a string so the following [line](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/exceptions.py#L80) throws an exception `'str' object has no attribute 'get'` on the second get:
```
if self._error.get('error_data', {}).get('blame_field_specs'):
```

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
