### ISSUE TITLE
AdGroup in 2.10.1

### ISSUE THREAD

**Issue by cameres** [facebook/facebook-python-business-sdk#410]
Hello,

I'm using the newest version (2.10.1 as of this issue) and am having difficulties finding the AdGroup class referred to in earlier releases. Ideally I'd like to be able to access the AdGroup like how the endpoint is accessible from the [PHP API](https://developers.facebook.com/docs/marketing-api/reference/ad-account-group/v2.10). Is there an equivalent class in 2.10.1 or will it be released at some point in the future.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
