### ISSUE TITLE
Exception from Error 190 Subcode 490 Isn't Raised Correctly

### ISSUE THREAD

**Issue by chetmancini** [facebook/facebook-python-business-sdk#411]
I have a request coming back with the following data:
```
{u'code': 190, u'error_subcode': 490, u'error_data': u'{"checkpoint_flow_id":"207799259245384","checkpoint_content_id":"0"}', u'message': u'Error validating access token: The user is enrolled in a blocking, logged-in checkpoint', u'type': u'OAuthException', u'fbtrace_id': u'Dg5bXT267xL'}
{u'error': {u'code': 190, u'error_subcode': 490, u'error_data': u'{"checkpoint_flow_id":"207799259245384","checkpoint_content_id":"0"}', u'message': u'Error validating access token: The user is enrolled in a blocking, logged-in checkpoint', u'type': u'OAuthException', u'fbtrace_id': u'Dg5bXT267xL'}}
```
When I print the value of `self._error and self._body` inspecting from `exceptions.py` line 80.

Rather than give me back that exception data, I get this:

```
<long stacktrace>
if self._error.get('error_data', {}).get('blame_field_specs'):
AttributeError: 'unicode' object has no attribute 'get'
```

I believe in this case all the error cases aren't matching so it falls through to line 80, and in this case `error_data` seems to be a json-encoded string, not a Python object. It may be an issue on the backend but maybe this case could be handled safely by checking the type before retrieving `blame_field_specs`, and passing the info through otherwise.

Thanks.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
