### ISSUE TITLE
Dynamic Creative Optimization - cannot upload website_url and call_to_action

### ISSUE THREAD

**Issue by fai-huntrakool** [facebook/facebook-python-business-sdk#413]
Hey, I'm trying to create asset feed for dynamic creative optimization. I follow everything on https://developers.facebook.com/docs/marketing-api/asset-feed and it works very well on graph api.

The problem comes when I try this on python, though it doesn't return me any errors.

params={
'link_urls':[{'website_url':'https://itunes.apple.com/app/idxxxxx'}],
'call_to_action_types':['SHOP_NOW'],
'images':[{'hash':image1['hash'], 'url_tags':'image=image1'},{'hash':image2['hash'], 'url_tags':'image=image2'}],
'bodies':[{'text':'Begin Your Adventure'}, {'text':'Once a Trainer, always a Trainer.'}],
'titles':[{'text':'Level Up'}, {'text':'Swipe to evolve'}],
'descriptions':[{'text':'Begin Your Adventure'}],
'ad_formats':['SINGLE_IMAGE'],
}
request = FacebookRequest(
            node_id=account_id,
            method='POST',
            endpoint='/adasset_feeds',
            target_class=AdAccount,
            api_type='NODE',
        )
request.add_params(params)
request.execute()

When I checked into the adasset_feeds on GraphAPI, I found that images,bodies,titles,descriptions and ad_formats are successfully added to the feed but call_to_action_types and link_urls don't show up.

Please suggest me on how to make this script work.  

Thanks

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
