### ISSUE TITLE
User request limit reached during internal cursor based pagination

### ISSUE THREAD

**Issue by mandrews** [facebook/facebook-python-business-sdk#416]
For accounts with a moderate number of ads (page=25)- the following code triggers a "User request limit reached" exception:

```python
for ad in account.get_ads():
   print(ad)
```

Stacktrace:
```
  File "/usr/local/lib/python3.6/site-packages/facebookads/adobjects/adaccount.py", line 721, in get_ads
    return request.execute()
  File "/usr/local/lib/python3.6/site-packages/facebookads/api.py", line 657, in execute
    cursor.load_next_page()
  File "/usr/local/lib/python3.6/site-packages/facebookads/api.py", line 801, in load_next_page
    params=self.params,
  File "/usr/local/lib/python3.6/site-packages/facebookads/api.py", line 330, in call
    raise fb_response.error()
facebookads.exceptions.FacebookRequestError:

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v2.11/act_XXX/ads
  Params:  {'fields': 'adlabels', 'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#17) User request limit reached",
        "type": "OAuthException",
        "is_transient": true,
        "code": 17,
        "fbtrace_id": "HsDsvTm9trr"
      }
    }
```

Also, it doesn't seem possible to workaround this limitation, as all objects appear to be batched in memory:
```
import time
n = 0
for ad in self.account.get_ads(fields=self._ad_fields()):
    if n % 25 == 0:
        time.sleep(2)
    yield ad
    n += 1
```

It might make sense to sleep with some backoff factor when a "code 17" is returned.

Related issue:
https://github.com/facebook/facebook-python-ads-sdk/issues/203

**Comment by windsfantasy6** [comment]
Hi,
I don't really get what you want to explain. Maybe you call the API too much and get throttled?

**Comment by mandrews** [comment]
@windsfantasy6 yes I am getting throttled. My point is that there is no way for me to backoff / wait while using the SDK.

**Comment by Alston-DataEngineer** [comment]
Hey Mandrews, Did your problems get been fixed? I have the same issue as you and I though it may release the limitation some hours later and it's not.

**Comment by codytwinton** [comment]
Hey, thanks for your submitting this issue! This appears to be an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
