### ISSUE TITLE
Some ads not returned when breakdowns=[country]

### ISSUE THREAD

**Issue by mccomplete** [facebook/facebook-python-business-sdk#429]
I am making a call to AdAccount.get_insights_async() and paging over the results.  When I pass "breakdowns": [AdsInsights.Breakdowns.country] in the params dict, I get 96 ads.  When I pass the params dict without breakdowns, I get 100 ads.  The ads that are not returned are responsible for about 1/3 of the spend of the account.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
