### ISSUE TITLE
CustomAudience.add_users() fails with `This audience was created from data source FILE_IMPORTED.MULTI_HASHES, which does not support data source FILE_IMPORTED.HASHES_OR_USER_IDS.`

### ISSUE THREAD

**Issue by mikhaildubov** [facebook/facebook-python-business-sdk#433]
Here is a simple `add_users` example, similar to the one in the docs: https://developers.facebook.com/docs/marketing-api/reference/sdks/python/custom-audience

```
custom_audience = CustomAudience('6040236453040')
custom_audience.add_users(
    schema=CustomAudience.Schema.email_hash,
    users=['test1@example.com', 'test2@example.com']
)
```

It fails with with the following:

```
  Status:  400
  Response:
    {
      "error": {
        "message": "(#2650) Failed to update the custom audience: This audience was created from data source FILE_IMPORTED.MULTI_HASHES, which does not support data source FILE_IMPORTED.HASHES_OR_USER_IDS.",
        "type": "OAuthException",
        "code": 2650,
        "fbtrace_id": "AzJKjF6OyDj"
      }
    }
```

There have been a few discussions around this issue online that outlined that the API expects not just a list of emails but a list of lists:
https://qiita.com/sutoh/items/44a0f66ed29ebe3e1c68

i.e.

```
curl - F 'payload = {"schema": ["EMAIL_SHA 256"], "data": [  
  ["EMAIL"], ["EMAIL"]]  
  } '\
  -F 'access_token = <AccessToken>' \
```

However, if you try to do it in Python SDK:

```
custom_audience = CustomAudience('6040236453040')
custom_audience.add_users(
    schema=CustomAudience.Schema.email_hash,
    users=[['test1@example.com'], ['test2@example.com']]
)
```

You get an error at the preprocessing stage:
```
  File "/ve/lib/python3.6/site-packages/facebookads/adobjects/helpers/customaudiencemixin.py", line 208, in add_users
    session,
  File "/ve/lib/python3.6/site-packages/facebookads/adobjects/helpers/customaudiencemixin.py", line 67, in format_params
    user = user.strip(" \t\r\n\0\x0B.").lower()
AttributeError: 'list' object has no attribute 'strip'
```

**Comment by mikhaildubov** [comment]
Okay so it looks like this issue appears when the custom audience has been created manually in the Ads dashboard but goes away if you create one using the API. I wish this was articulated clearer in the docs...

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
