### ISSUE TITLE
AbstractObject equality always False

### ISSUE THREAD

**Issue by simonschmidt** [facebook/facebook-python-business-sdk#439]
Currently `AbstractObject`s that are not also `AbtsractCrudObject` always compare as `False`, e.g.

```
from facebookads.adobjects.targeting import Targeting

targeting = Targeting()
targeting == targeting  # False
```

In `facebookads/adobjects/abstractobject.py`:

```
    def __eq__(self, other):
        return other is not None and 'export_all_data' in other and \
            self.export_all_data() == other.export_all_data()
```

It looks like it should be `hasattr(other, 'export_all_data')` instead of `in`.
The code looks autogenerated, I'm not sure if a PR changing those lines is the right place to fix it.
It might also make sense to introduce a type-check similar to the `__eq__` in `AbstractCrudObject`

**Comment by jingping2015** [comment]
this already fixed and should be available for next release.
