### ISSUE TITLE
Add to Audience with format_params doesn't respect LOOKALIKE_VALUE

### ISSUE THREAD

**Issue by chetmancini** [facebook/facebook-python-business-sdk#441]
When adding users to a lookalike value-based seed custom audience, one must pass a schema that contains the string `LOOKALIKE_VALUE`, like:
`[CustomAudience.Schema.MultiKeySchema.email, 'LOOKALIKE_VALUE''`.

https://developers.facebook.com/docs/marketing-api/value-based-lookalike-audience-targeting

And then users are added with that value passed as a numerical value, like an `int` or `float`.

The problem comes when a developer wishes to use the SDK to automatically format and hash params. The `format_params` function assumes that all values are strings when it runs:
```
key = key.strip(" \t\r\n\0\x0B.").lower()
key = CustomAudienceMixin.normalize_key(key_name, str(key))
```

The only workaround is to manually hash all values and invoke add with `pre_hashed=True`.

With a small enhancement, this package could make populating a value-based audience much simpler and allow end developers to use the formatting code already written.

**Comment by albertabello** [comment]
Do we have any update on this issue?

**Comment by kickerbear** [comment]
@chetmancini What's the status on the PR you created in February?

**Comment by chetmancini** [comment]
@kickerbear Hmm, yeah I haven't heard anything from the maintainers so I ended up just sort of monkeypatching it over for my own company. It took a long time to merge my last PR so I imagine there's a big backlog on FB's side. It looks like there are some conflicts, so I'm happy to rebase/reintegrate my changes once I get the thumbs up from someone able and willing to merge.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
