### ISSUE TITLE
how to add sandbox account

### ISSUE THREAD

**Issue by sushilrawat01** [facebook/facebook-python-business-sdk#443]
![business settings 1](https://user-images.githubusercontent.com/29747476/36072181-4a064f26-0f41-11e8-890d-7c441d50101e.png)

screen shot says "The admin of this ad account needs to approve your request. If you're the admin, please go to Ads Manager and approve this request." 
how should i approve the request . i don't see any

**Comment by tosolveit** [comment]
I think you should go to facebook developers page and login your app first, once you've logged in go to the products / marketing api, there you will see sandbox adaccount management settings, add a sandbox account, after that you gotta approve some aggrement at the actions column on the right of the sandbox adaccount managements settings, I think at this point you will be able to use your sandbox account, I had the similar problem and after approval I am able to use the account.

I used [this](https://developers.facebook.com/ads/blog/post/2016/10/19/sandbox-ad-accounts/) page and it was helpful for me.
