### ISSUE TITLE
Add Business-to-Business Functions

### ISSUE THREAD

**Issue by dadoeyad** [facebook/facebook-python-business-sdk#447]
I wanted to open a pull request but then I saw that we can't edit auto generated classes :/
I'd like to request adding the business to business functions described here: https://developers.facebook.com/docs/marketing-api/businessmanager/assets#b2b

I mainly need add ad account and pages to a business manager.

Thanks!

**Comment by brandonkane** [comment]
👍 Totally agree - everything that is part of the standard API should be included in the SDK.  Especially since it is auto generated, there is really no reason to exclude any of the marketing-api endpoints.

**Comment by shootingsyh** [comment]
Please try the latest v3.1 and see if everything you need is there. Open new issues for features you still want.
