### ISSUE TITLE
Missing values in enums accross the whole codebase

### ISSUE THREAD

**Issue by x8lucas8x** [facebook/facebook-python-business-sdk#450]
That's not the first time I'm trying to get a value from an enum, which is listed in the documentation, and found that it's not there. For instance, SEE_DETAILS and WATCH_MORE is supported since https://developers.facebook.com/docs/marketing-api/reference/ad-creative-link-data-call-to-action/v2.10, but it hasn't made it's way to this lib even though we are on v2.12 already. I'd expect to see those in AdCreativeLinkDataCallToAction.Type. Also, there is no Ad.Field.creative_id even though that's returned by the GraphQL endpoint for Ads.

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
