### ISSUE TITLE
Issue passing mobile_advertising_id through CustomAudience.Schema

### ISSUE THREAD

**Issue by adeedchoudhury** [facebook/facebook-python-business-sdk#451]
Hello,

I have a list of mobile_user_id's in a pandas dataframe titled `users`. I'd like to add these users to a pre-created Custom Audience. Here is the code I am using:

```
from facebookads.adobjects.customaudience import CustomAudience
schema = CustomAudience.Schema.mobile_advertiser_id
users = data
custom_audience = CustomAudience(audience)
response = custom_audience.add_users(
    schema=CustomAudience.Schema.mobile_advertiser_id,
    users=data)
```

However when I run this code, I get an error `TypeError: string indices must be integers
`. This doesn't make sense to me since mobile_advertising_ids are inherently strings. Furthermore, 
if i hash these ids, they are still identified as strings so I am not sure how I should proceed.

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
