### ISSUE TITLE
how to get "summary" in AdsInsights with filtering by Campaign Objective

### ISSUE THREAD

**Issue by tranngoctan18** [facebook/facebook-python-business-sdk#452]
If I choose to filter by "objective". The "summary" in the response body does not show. Why is that?.  I search for that in API and find no clue. Could anyone please help me figure it out?

![screen shot 2018-03-28 at 10 31 31 am](https://user-images.githubusercontent.com/24957485/38007354-3e6d0920-3273-11e8-810e-39dda25e195c.png)

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
