### ISSUE TITLE
How to update image advert or image creative's attributes

### ISSUE THREAD

**Issue by projects-logiciel** [facebook/facebook-python-business-sdk#454]
I am trying to update imzage and headline of advert. API return success response but link data attributes are not updated.

```
$advertisement = new Ad(23842735796150501);
advertisement->creative = [
       [object_type] => PHOTO
       [object_story_spec] => [
              [link_data] => Array
              [
                      [picture] => http://www.thehindu.com/migration_catalog/article15485191.ece/alternates/FREE_660/08pp%20cover.ART0_GIL21OBG7.1+08pp_Sylvan_County.jpg
              ]         
        ]
]

$advertisement->update();
```

Also tried same from Graph API Explorer

http://graph.facebook.com/2.12/23842735796150501

Request Param

```
['object_story_spec']['link_data']['picture'] = http://www.thehindu.com/migration_catalog/article15485191.ece/alternates/FREE_660/08pp%20cover.ART0_GIL21OBG7.1+08pp_Sylvan_County.jpg
```

Response
```
{
  "success": true
}
```

Graph api explorer Session url - https://developers.facebook.com/tools/explorer/202385023516039/?session_id=820536021463514

According to this ref link https://github.com/facebook/facebook-python-ads-sdk/issues/214Creatives are immutable objects, meaning once created none of their properties can be changed, Is that right ? Is yes the what is that appropriate way to change the image of advert.

**Comment by ellentao** [comment]
Hey,
Thanks for your comments! Actually the Business SDK will return the same data with Facebook Graph API. As you mentioned, the API also returns TRUE while the image is not updated. Then I suppose this is not a bug on SDK side. Could you please report the bug on developer site https://developers.facebook.com/support/bugs/? Thanks!
