### ISSUE TITLE
UserWarning for AdsPixelStatsResult.Aggregation with event_total_counts

### ISSUE THREAD

**Issue by cas--** [facebook/facebook-python-business-sdk#455]
I encountered the following warning when using enum `event_total_counts` for aggregation parameter.

```
lib/python3.5/site-packages/facebookads/utils/api_utils.py:30: UserWarning: value of aggregation might not be compatible.  Expect aggregation_enum;  got <class 'str'>
  warnings.warn(message)
```

Looking at https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adspixelstatsresult.py#L45 the Aggregation class is missing `event_total_counts`, along with `pii_keys` and `pii_stats` as detailed here: https://developers.facebook.com/docs/marketing-api/reference/ads-pixel/stats/#Reading

**Comment by jingping2015** [comment]
This should already fixed.
