### ISSUE TITLE
AdAccount get_insights not returning all ads

### ISSUE THREAD

**Issue by Nuthalapati** [facebook/facebook-python-business-sdk#457]
We have several ad accounts and I'm trying to pull insights for each ad account and observe that some of the ads were missing in the output. 
` 'time_range': {'since': '2018-02-01', 'until': '2018-02-02'},
            'level': 'ad',
            'time_increment': '1'`
When I try to pull the data from UI in AdsManager its missing there too.

**Comment by ellentao** [comment]
Thanks for your comments! Actually the Business SDK will return the same data with Facebook Graph API. As you mentioned, the data is missing in AdsManager too, then it means the error is not on Business SDK part. Could you please report the bug on developer site https://developers.facebook.com/support/bugs/? Thanks!
