### ISSUE TITLE
Issues with OAuth

### ISSUE THREAD

**Issue by dgilbs** [facebook/facebook-python-business-sdk#460]
Right now I have the following code:

from facebookads.api import FacebookAdsApi
from facebookads.adobjects.adaccountuser import AdAccountUser
from facebookads.adobjects.adaccount import AdAccount

FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)

me = AdAccountUser(fbid='me')
me.get_ad_accounts()

account = AdAccount("act_***************")
account.get_activities()

I'm getting an error on the AdAccountUser that says "An active access token must be used to query information about the current user"

And I'm getting a "service temporarily unavailable error" on the AdAccount part. 

Any ideas? Nothing that I'm finding online seems to be working.

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
