### ISSUE TITLE
Reporting on Orders (Beta) broken. Unable to fetch conversions

### ISSUE THREAD

**Issue by ssundara-nw** [facebook/facebook-python-business-sdk#461]
Hi Guys! We are using a BETA feature form https://developers.facebook.com/docs/marketing-api/insights . Reporting on Orders (Beta)

We recently updgraded facebookads API (Python SDK) to version 2.11 and Reporting on Orders (Beta) seems to be broken. We are unable to fetch conversion attribution data anymore.

Reporting on Orders (Beta) is a simple server to server call and doesnt have direct dependency on SDK itself.

https://graph.facebook.com/<API_VERSION>/<BUSINESS_ID>/order_id_attributions

{"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.11.","type":"OAuthException","code":2635,"fbtrace_id":"<>"}}

Can you please help us here and suggest whom we can contact ?

**Comment by shootingsyh** [comment]
@ssundara-nw do you mean calling the API directly fail or calling the sdk fail? It seems to me that you are calling an old version of the API older than 2.11? Can you share some of your code?

**Comment by codytwinton** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
