### ISSUE TITLE
Expose rate limiting data

### ISSUE THREAD

**Issue by jon-rtr** [facebook/facebook-python-business-sdk#463]
Right now, I have no way to understand how close I am to hitting limits, so at the very least the library should log that information. Even better would be to expose the values, so my app can determine when and how to back off.

**Comment by codytwinton** [comment]
This feature request doesn't appear to be actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
