### ISSUE TITLE
Issue in schedule and update_schedule on productcatalog.py

### ISSUE THREAD

**Issue by agustinscigliano** [facebook/facebook-python-business-sdk#467]
There is an issue in the types for schedule and update_schedule.

`    def create_product_feed(self, fields=None, params=None, batch=None, pending=False):
        from facebookads.adobjects.productfeed import ProductFeed
        param_types = {
            'country': 'string',
            'default_currency': 'string',
            'deletion_enabled': 'bool',
            'delimiter': 'delimiter_enum',
            'encoding': 'encoding_enum',
            'file_name': 'string',
            'name': 'string',
            'quoted_fields_mode': 'quoted_fields_mode_enum',
            'rules': 'list<string>',
            'schedule': 'string',
            'update_schedule': 'string',
        }`

The types expected are string and in the doc : https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog it says it is a dic. 
I dont know why, but this makes the schedule and update_schedule to ignore the hour and minutes params, although the `url` and `interval` fields work.

**Comment by agustinscigliano** [comment]
There is no error.. it ignores them. Also, in the doc `https://developers.facebook.com/docs/marketing-api/reference/product-feed-schedule/` it says that you can set the timezone, but there is no such param. How can i set the timezone in the schedule and update_schedule?

**Comment by agustinscigliano** [comment]
I tried using the Python Business SDK example you mentioned above, but it has the same error. The hour param does not set it correctly. In the example it is set for Daily interval at 22hs but it sets it for Daily interval at 2 AM.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
