### ISSUE TITLE
bootstrap.py references deprecated facebookads.objects

### ISSUE THREAD

**Issue by howardic** [facebook/facebook-python-business-sdk#468]
In bootstrap.py, every time I pull a new version I have to update:

`from facebookads.objects import *`
to
`fromfacebookads.adobjects import *`

Isn't objects deprecated?

**Comment by abhishmitra** [comment]
Same issue here. In examples/read_ads.py

Please advise.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
