### ISSUE TITLE
Getting all FB pages tied to app in v3.0

### ISSUE THREAD

**Issue by zeraqis** [facebook/facebook-python-business-sdk#471]
I'm trying to get a list of all the pages tied to my Ad Account with the following code:
```
    from facebook_business.adobjects.adaccountuser import AdAccountUser
    from facebook_business import FacebookAdsApi

    api = FacebookAdsApi.init(FB_APP_ID, FB_SECRET, FB_TOKEN)
    fb = AdAccountUser(fbid='me')
    fb.get_pages()
```

This code has been working fine till a week ago but now I get the following error:
  
```
      Message: Call was not successful
      Method:  GET
      Path:    https://graph.facebook.com/v2.10/me/owned_pages
      Params:  {'summary': 'true'}
    
      Status:  400
      Response:
        {
          "error": {
            "message": "(#100) Tried accessing nonexisting field (owned_pages) on node type (User)",
            "type": "OAuthException",
            "code": 100,
            "fbtrace_id": "Fc6tw+qJT2W"
          }
        }
```

The new `facebook_business` sdk still has the `get_pages()` method in the [AdAccountUserMixin](https://github.com/facebook/facebook-python-business-sdk/blob/fcc2fe015136a9222334b364c3003a56475ec76c/facebook_business/adobjects/helpers/adaccountusermixin.py)

In addition, the official [documentation](https://developers.facebook.com/docs/pages/getting-started) (an example of 2.10), if read towards the end says

> To get a list of page_ids in the Graph API Explorer send a GET request to me?fields=id,name,accounts where me is you with your User Access Token. This will return a list of pages you manage.

Which in itself is not very descriptive but I presume it is similar to what I am attempting here.

I am aware of the recent changes to the Pages API requiring approval from FB for apps to continue accessing information but here I would just like to list the pages tied to the account.

This seems to be not very clear from documentation I was able to find, how would I go about in doing this?

**Comment by ellentao** [comment]
Hi, thanks for your comment! You could use GET {user_id}/accounts, with your user access token, to get the pages that linked to your account.

**Comment by neilsh** [comment]
@ellentao  Can we re-open this issue? It seems like the function should either be fixed or removed, to help avoid user confusion/surprise.

**Comment by flyfj** [comment]
we need a more clear documentation of the python sdk
