### ISSUE TITLE
Paging Over an AdAccount get_ads() Resultset

### ISSUE THREAD

**Issue by JamesCLloyd** [facebook/facebook-python-business-sdk#474]
Is there a way in the SDK to either 

a) Filter the results of an AdAccount `get_ads()` call.
b) Page over the results.

I'm getting this response:
```
  Status:  500
  Response:
    {
      "error": {
        "message": "Please reduce the amount of data you're asking for, then retry your request",
        "code": 1
      }
    }
```

I can change the 'limit' parameter to something low (say 500) but can't then get at the remaining results.

I can't see that **async** is available for these calls (unlike the `get_insights()` methods) and the insights don't have the fields I need otherwise I'd use that.

Any help much appreciated.

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
