### ISSUE TITLE
No assigned_ad_accounts endpoint

### ISSUE THREAD

**Issue by bnormoyle** [facebook/facebook-python-business-sdk#479]
With the deprecation of the adaccounts endpoint, this library has no mechanism for a user to get the ad accounts they have access to. The graph exposes this via assigned_ad_accounts, but this library does not appear to support that.

**Comment by bnormoyle** [comment]
Yes - that hits the adaccounts endpoint, which is deprecated.

**Comment by vicdus** [comment]
We will support this endpoint soon :)

**Comment by bnormoyle** [comment]
Why is this closed? The issue isn't resolved, the endpoint isn't supported yet.
