### ISSUE TITLE
Get Adsets data (Insights data, metafields) in a single request

### ISSUE THREAD

**Issue by tranngoctan18** [facebook/facebook-python-business-sdk#480]
I like to get Adsets fields (name, daily_budget, status) along with Adset Insights (spend, impressions, actions). I found that we could use Graph API with nested fields like this.

https://graph.facebook.com/v3.0/act_<AD_ACCOUNT_ID>/adsets?fields=insights.time_range({'until':'2018-06-12', 'since':'2018-06-11'}){impressions,actions,spend},name,daily_budget,effective_status

How can we make this call in Python SDK?

Thank you,

**Comment by jingping2015** [comment]
Please take look example here https://developers.facebook.com/docs/marketing-api/reference/ad-account/v3.1
