### ISSUE TITLE
Add users to Custom Audience by phone numbers did not work?

### ISSUE THREAD

**Issue by tranngoctan18** [facebook/facebook-python-business-sdk#481]
I use this method below of CustomAudience (CustomAudienceMixin.add_users) to add users by phone number (10k phone numbers), but it did not work. Do I use this method the wrong way?

![screen shot 2018-06-15 at 12 17 04 pm](https://user-images.githubusercontent.com/24957485/41451268-41125a98-7096-11e8-82b6-68991812fdea.png)

**Comment by davepmarshall** [comment]
Do you see any error when running this? The code looks fine to me.
Do you define `audience` beforehand with something like 
`audience = CustomAudience('1234567890')`

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
