### ISSUE TITLE
Addition of 3-Second Video Views to the Insights API

### ISSUE THREAD

**Issue by jelloslinger** [facebook/facebook-python-business-sdk#482]
This is a feature request to add a metric to the Insights API.  Currently, you can pull 3-Second Video Views from the front-end Ads Manager and export it in a report.  However, this metric is not accessible in the Insights API.  Will this be added?

**Comment by jingping2015** [comment]
Hi,
If graph api already have this functionality, please link the reference doc/api call. We can add this feature in feature. 
If no, please report this to https://developers.facebook.com/support/bugs/ Thanks!
