### ISSUE TITLE
using async as argument raises SyntaxError in Python 3.7.0

### ISSUE THREAD

**Issue by ntnam11** [facebook/facebook-python-business-sdk#484]
I've just updated my Python from 3.6.3 to 3.7 and tried to run get_insight(...):
![image](https://user-images.githubusercontent.com/40453800/42082240-acd20de8-7bb1-11e8-896e-0cec49d984fb.png)
From Python 3.7, `async` and `await` become reserved keywords:
https://docs.python.org/3.7/whatsnew/3.7.html#changes-in-python-behavior
Hope this will be fixed asap

**Comment by alternativshik** [comment]
I've fixed this issue in #491

**Comment by jingping2015** [comment]
this should already fix in our current release. Thanks for reporting this issue.
