### ISSUE TITLE
API docs (and hence the SDK) mispelling (?) on daily_imps

### ISSUE THREAD

**Issue by bra-fsn** [facebook/facebook-python-business-sdk#486]
adset.py contains a Field named "daily_imps" and the API docs also have this:
https://developers.facebook.com/docs/marketing-api/reference/ad-campaign/v3.0

But as others have already noted this is wrong, if you want to fetch "daily_imps" field, the API fails with:
```
  Status:  400
  Response:
    {
      "error": {
        "message": "(#100) Tried accessing nonexisting field (daily_imps) on node type (AdCampaign)", 
        "code": 100, 
        "type": "OAuthException", 
        "fbtrace_id": "Du/8y5ur8Cq"
      }
    }
```
See:
https://github.com/facebook/facebook-php-business-sdk/issues/294

Changing "daily_imps" to "daily_imp" in the code makes the error go away.

**Comment by kalendae** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
