### ISSUE TITLE
the keyword 'async' is not working in python 3.7 (get_insights)

### ISSUE THREAD

**Issue by geusan** [facebook/facebook-python-business-sdk#487]
![image](https://user-images.githubusercontent.com/16855210/42366565-7206a670-813c-11e8-9571-8173e221258d.png)

we can't use keyword 'async'  in python 3.7
'async' and 'await' are reserved words

[what's new in python 3.7](https://docs.python.org/3/whatsnew/3.7.html)

**Comment by alternativshik** [comment]
I've fixed this issue in #491

**Comment by jingping2015** [comment]
We already rename it to is_async 
https://github.com/facebook/facebook-python-business-sdk/blob/ccef9154d2c201ef71ea5ac94326b9f10b122e56/facebook_business/adobjects/adaccount.py#L1924

**Comment by revmischa** [comment]
New pypi release? Please?
