### ISSUE TITLE
url_override not really overriding

### ISSUE THREAD

**Issue by howardic** [facebook/facebook-python-business-sdk#490]
https://github.com/facebook/facebook-python-business-sdk/blob/e2f279a62b7e6c7fd30a080b4be8103c7303a715/facebook_business/api.py#L285

It really feels like this line should read:

     url_override or self._session.GRAPH,

since GRAPH is a string constant and never False

**Comment by jingping2015** [comment]
This issue already fixed https://github.com/facebook/facebook-python-business-sdk/blob/ccef9154d2c201ef71ea5ac94326b9f10b122e56/facebook_business/api.py#L285
