### ISSUE TITLE
PyPi and Github Repo Mismatch

### ISSUE THREAD

**Issue by brandonkane** [facebook/facebook-python-business-sdk#493]
There was a new version (3.0.4) pushed to PyPi 3 days ago.  There were no code changes in this repo, and no releases/tags have been added since the initial 3.0.0 release.  With the 3.0.1, 3.0.2, 3.0.3 releases that @vicdus committed, there is no tag in GitHub, but at least the commits are there so we can see the diffs.  With 3.0.4 there is only a package in PyPi.

So we have no way to know what is in this new release, or if it was even published by Facebook since its code does not appear in this official repo.  

https://pypi.org/project/facebook_business/3.0.4/#history

Can someone clarify the release process and make sure that this repo is kept in sync with PyPi?

**Comment by brandonkane** [comment]
According to this repo, the latest version is still 3.0.0, but on [PyPI](https://pypi.org/project/facebook_business/#history) the latest version is 3.1.2.

@codytwinton - you've been closing off the older tickets which are no longer relevant, which is great, but would be good if there could be some review of the open ones to get them resolved.

**Comment by codytwinton** [comment]
@brandonkane - We are working hard to resolve/close up outstanding issues for this SDK. We've been closing out old/outdated issues first, so we can focus on the relevant, current issues.

**Comment by brandonkane** [comment]
@codytwinton awesome - thanks.  This one should be pretty easy, @shootingsyh did the last release tag in GitHub for 3.0.0, looks like its just a matter of making sure the auto update that pushes each patch releases also creates a release tag in GitHub.

**Comment by jingping2015** [comment]
Looks like it is updated, https://pypi.org/project/facebook_business/. Thanks for reporting this bug.

**Comment by brandonkane** [comment]
@jingping2015 No, it isn't.  PyPi has been correct the whole time, but there are no tags in GitHub for the releases.  Still says 3.0.0 is the current release, which is very incorrect.  It also means we can't see the diffs between releases, and is just super confusing in general.

See https://github.com/facebook/facebook-python-business-sdk/releases - should match the PyPi link you sent.  Please reopen

**Comment by codytwinton** [comment]
@brandonkane - Yes, we are working on automating this process. Should be live very shortly.
