### ISSUE TITLE
Class AdAccount.Fields has no relation to the fields described in documentation

### ISSUE THREAD

**Issue by embatbr** [facebook/facebook-python-business-sdk#494]
When reading the [code](https://github.com/facebook/facebook-python-business-sdk/blob/e2f279a62b7e6c7fd30a080b4be8103c7303a715/facebook_business/adobjects/adaccount.py#L47), I see that some fields described in the API documentation are missing and vice-versa.

**Comment by jingping2015** [comment]
which fields are you talking about ?

**Comment by jingping2015** [comment]
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.
