### ISSUE TITLE
Ad Campaign get_insights by date and country not working

### ISSUE THREAD

**Issue by Sky-Nik** [facebook/facebook-python-business-sdk#496]
I am trying to get insights about a specific ad campaign on specific date broken down by country. My code is as follows:
```
_fields=['impressions', 'spend']
_params={'breakdowns':'country',
         'time_range': {'since': '2018-07-15', 
                        'until': '2018-07-15'}}
campaign.get_insights(fileds=_fields, params=_params)
```
I get the following error: 
```
UserWarning: value of breakdowns might not be compatible.
Expect list<breakdowns_enum>;  got <class 'str'>
```
Is there anything I am doing wrong, or is it a mistake in sdk?

**Comment by ntnam11** [comment]
The error said that `breakdowns` parameters must be a list. Try changing `'breakdowns': 'country'` to `'breakdowns': ['country']`

**Comment by jingping2015** [comment]
close it since @ntnam11  provide  a correct way to fix it.
