### ISSUE TITLE
Page.get_leadgen_forms disappeared in 3.0

### ISSUE THREAD

**Issue by aparakian** [facebook/facebook-python-business-sdk#498]
This method has always been present in the SDK (See this [commit](https://github.com/facebook/facebook-python-business-sdk/commit/7297b11afaf5572a65c636cff782864d908146fe#diff-e544288e1fedd630c9d60e20fb3e89b3R55) introduced it) and is well available on the API. However it disappeared from the new SDK 3.0.
Is there any good reasons for it? 
Do you want me to make a PR to reintroduce it?
Thanks for your answer.

**Comment by aparakian** [comment]
Basically we need this [method](https://github.com/facebook/facebook-python-business-sdk/blob/master/facebook_business/adobjects/page.py#L1600-L1642) in `method='GET'`

**Comment by jingping2015** [comment]
We already fix this in our new release. Thanks for reporting this bug.
