### ISSUE TITLE
Many GET methods are missing from the SDK 3.0

### ISSUE THREAD

**Issue by aparakian** [facebook/facebook-python-business-sdk#499]
Here is another occurence of GET method missing:
You have a `create_subscribed_app` and `delete_subscribed_apps` [here](https://github.com/facebook/facebook-python-business-sdk/blob/master/facebook_business/adobjects/page.py#L3098-L3150) but you don't provide the `get_subscribed_apps` method while this is authorized on the API. 
Why?

**Comment by aparakian** [comment]
Same for `get_lead_gen_whitelisted_users` while `create_lead_gen_whitelisted_user` and `delete_whitelisted_users` exist [here](https://github.com/facebook/facebook-python-business-sdk/blob/master/facebook_business/adobjects/page.py#L1680-L1735)...

**Comment by aparakian** [comment]
I mention "and others" because at least `get_lead_gen_forms` is in the same situation as mentioned in #498.
I feel like many many `GET` methods are missing...

**Comment by bnormoyle** [comment]
I mentioned in #479 (which got unceremoniously closed) that assigned_ad_accounts is also missing.

**Comment by aparakian** [comment]
Good luck @bnormoyle 
I have very little hope with issues being resolved in this repo, I hope you can update your fork with the missing methods, that makes the merge conflicts a bit painful but at least you can fix your stuffs temporarily...

**Comment by jingping2015** [comment]
In our new release, we fix the bugs for missing endpoint. If you still have this issue, please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/). Thanks!
