### ISSUE TITLE
Classes not serializable by pickle

### ISSUE THREAD

**Issue by rmgpinto** [facebook/facebook-python-business-sdk#501]
When airflow tries to serialize an array of AdAccount objects, it fails with the error:
...
value = pickle.dumps(value)
TypeError: can't pickle dict_values objects

Can you make the classes serializable?

**Comment by jingping2015** [comment]
How you get `value` ?

**Comment by jingping2015** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
