### ISSUE TITLE
No assigned_ad_accounts endpoint

### ISSUE THREAD

**Issue by bnormoyle** [facebook/facebook-python-business-sdk#503]
My issue #479 was closed with a promise it'll be in 'soon', but:

1) That's not a justification to close a real issue 
2) It's been two months and the broken endpoint is still not deprecated in this codebase and the correct one still isn't being used.

Please add the assigned_ad_accounts endpoint.

**Comment by jingping2015** [comment]
Do you want to get user's adaccounts ?
Like this 
```
user = User("...")
ad_accounts = user.get_ad_accounts();
print ad_accounts
```

Any error you got ?

**Comment by bnormoyle** [comment]
As I mentioned in the previous issue, that hits the adaccounts endpoint, which is deprecated. The new endpoint is assigned_ad_accounts.

**Comment by jingping2015** [comment]
This will be fixed in out next few release. Thanks for reporting this.
