### ISSUE TITLE
facebook_business/adobjects/abstractobject.py:59: return other is not None and hasattr(targeting, 'export_all_data') and \ <class 'NameError'>: name 'targeting' is not defined

### ISSUE THREAD

**Issue by abetomo** [facebook/facebook-python-business-sdk#504]
https://github.com/facebook/facebook-python-business-sdk/commit/dd8d9de4519f98feb5bfc3e9271d18be8110c6a6#diff-5c2ee73c9f7f6f616946f19e23a7dae9R58

It seems that the automatically generated code is wrong.

`hasattr(targeting, 'export_all_data')`

->

`hasattr(other, 'export_all_data')`

**Comment by jingping2015** [comment]
This should fix in our next release.
