### ISSUE TITLE
Deprecated Version

### ISSUE THREAD

**Issue by vnportnoy** [facebook/facebook-python-business-sdk#512]
I am getting this error when trying to do any request (used to work until a few days ago).

 You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0.

 Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v2.11/act_1394270470695081/insights
  Params:  {'fields': 'campaign_id,campaign_name,actions,impressions,spend', 'level': 'campaign', 'date_preset': 'yesterday'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0.",
        "type": "OAuthException",
        "fbtrace_id": "GR2g3Shc/Rd",
        "code": 2635
      }
    }

**Comment by jingping2015** [comment]
You should call api v3.0/v3.1 to solve your problem.

**Comment by vnportnoy** [comment]
How? I never set that on code.

**Comment by brandonkane** [comment]
@vnportnoy Just upgrade your python package:
```
pip install facebook_business --upgrade
```

**Comment by bennicholes** [comment]
I have the same exact problem and I have updated via pip

```
 ❯ pip3 install facebook_business                                                                                                                             [17:53:16]
Collecting facebook_business
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python3.6/site-packages (from facebook_business) (1.11.0)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.6/site-packages (from facebook_business) (2.18.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->facebook_business) (2017.11.5)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->facebook_business) (3.0.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->facebook_business) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->facebook_business) (2.6)
Installing collected packages: facebook-business
Successfully installed facebook-business-3.1.2

 bnicholes@macbookpro14  ~/Desktop 
 ❯ python3 face.py                                                                                                                                            [17:53:27]
Traceback (most recent call last):
  File "face.py", line 20, in <module>
    audience = ad_account.create_custom_audience(params=params)
  File "/usr/local/lib/python3.6/site-packages/facebookads/adobjects/adaccount.py", line 1445, in create_custom_audience
    return request.execute()
  File "/usr/local/lib/python3.6/site-packages/facebookads/api.py", line 674, in execute
    api_version=self._api_version,
  File "/usr/local/lib/python3.6/site-packages/facebookads/api.py", line 332, in call
    raise fb_response.error()
facebookads.exceptions.FacebookRequestError:

  Message: Call was not successful
  Method:  POST
  Path:    https://graph.facebook.com/v2.11/act_1724169617634172/customaudiences
  Params:  {'subtype': 'CUSTOM', 'name': 'test', 'description': 'Bombora Direct Audience Injection'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "E7QVzE3VaAi"
      }
    }
```

**Comment by arorasudhir** [comment]
It looks like you are using facebookads. try this
change 
`from facebookads.api import FacebookAdsApi`
to 
`from facebook_business.api import FacebookAdsApi`

**Comment by STANAPI** [comment]
I'm also receiving the same error. Tried all the steps above, still not working

**Comment by arorasudhir** [comment]
pip uninstall facebookads
pip install facebook_business

**Comment by apurvis** [comment]
@jbb231 you probably need to somehow upgrade SSH - in the past few years a lot of auth has become less accepting of the old version of TLS.  unfortunately if you're on windows i can't really offer any help on how to actually do that..

**Comment by jingping2015** [comment]
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (Python), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
