### ISSUE TITLE
Ad Insights retrieval not working when using account with 2FA

### ISSUE THREAD

**Issue by nick-mccoy** [facebook/facebook-python-business-sdk#516]
Hello, I am getting an error when I try to retrieve insights for an account with 2FA (Two Factor Authentication) enabled:
```
{
  "error": {
    "message": "Two factor authentication required. User have to enter a code from SMS or TOTP code generator to pass 2fac. This could happen when accessing a 2fac-protected asset like a page that is owned by a 2fac-protected business manager.",
    "type": "OAuthException",
    "code": 415,
    "error_subcode": 1404120,
    "is_transient": false,
    "error_user_title": "Ask user to pass two factor authentication",
    "error_user_msg": "Unknown error",
    "fbtrace_id": "H8vqfjKyx+K"
  }
}
```
I tried re-authing and getting a new access token, and still had the same problem.  I've also created a [bug](https://developers.facebook.com/support/bugs/217724055764957/) on facebook's platform, but figured I'd create an issue here as well in case anyone is having the same problem or knows of a solution.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by nick-mccoy** [comment]
See the link in my post :)
