### ISSUE TITLE
Incorrect field validation

### ISSUE THREAD

**Issue by revmischa** [facebook/facebook-python-business-sdk#527]
https://github.com/facebook/facebook-python-business-sdk/issues/177
A lot of people would like this fixed

**Comment by jingping2015** [comment]
Hi, as mentioned in #177, you can add 
```
import warnings
warnings.simplefilter("ignore")
```
in your code to avoid show warning. 
Also we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (Python), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
