### ISSUE TITLE
Invalid appsecret_proof provided in the API argument

### ISSUE THREAD

**Issue by Umesh0071** [facebook/facebook-python-business-sdk#528]
Status:  400
  Response:
    {
      "error": {
        "message": "Invalid appsecret_proof provided in the API argument",
        "type": "GraphMethodException",
        "code": 100,
        "fbtrace_id": "E0JetexnRIn"
      }
    }

**Comment by ibnbay00** [comment]
just extend a token in:
[https://developers.facebook.com/tools/debug/accesstoken/](url)
Then debug ur new token in there. Finally use a new token for ur existing apps

**Comment by Umesh0071** [comment]
It works thanks
