### ISSUE TITLE
[New Pages Experience] 

### ISSUE THREAD

**Issue by amzar96** [facebook/facebook-python-business-sdk#652]
# Facebook Python Business SDK Issue
I am coming from [here](https://developers.facebook.com/docs/graph-api/reference/page/#Reading). However, I'm not sure whether this repo is cover the new Page or not?

**Comment by amzar96** [comment]
Understand it is achievable using graph request. But `from facebook_business.adobjects.page import Page` let's say I am using this method, how to get `fields=id,name,has_transitioned_to_new_page_experience` these?

**Comment by Just1B** [comment]
The snippet below should do the job for you 👍

You can check in the examples directory for more use cases : https://github.com/facebook/facebook-python-business-sdk/tree/main/examples

```python
from facebook_business.adobjects.page import Page
from facebook_business.api import FacebookAdsApi

access_token = '<ACCESS_TOKEN>'
id = '<PAGE_ID>'

FacebookAdsApi.init(access_token=access_token)

fields = [
  'id',
  'name',
  'has_transitioned_to_new_page_experience'
]

print(Page(id).api_get(fields=fields))
```

**Comment by amzar96** [comment]
Got it, thanks @Just1B . Just know that it doesn't support date range.

Thanks

**Comment by Just1B** [comment]
Depends on the type of data your are requesting, if you want to get page insights it does.

https://github.com/facebook/facebook-python-business-sdk/blob/main/facebook_business/adobjects/page.py#L2303

```python
from facebook_business.adobjects.page import Page
from facebook_business.api import FacebookAdsApi

access_token = '<ACCESS_TOKEN>'
id = '<PAGE_ID>'

FacebookAdsApi.init(access_token=access_token)

fields = [ ... ]

params = { 
  'date_preset' = '<YOUR_PRESET>
}

print(Page(id).get_insights(fields=fields, params=params))
```
