### ISSUE TITLE
Which versions of this Business SDK package correspond to the Marketing API versions?

### ISSUE THREAD

**Issue by nbro10** [facebook/facebook-python-business-sdk#654]
The answer may be obvious, but I'd like an official confirmation. 

I'd assume that the package version `x.y.z` corresponds to the API version `x` and that minor (`y`) and patch (`z`) versions of the package will just contain bug fixes. So, for example, the package version `16` or `16.0.1` will both make calls to the same Marketing API version 16. 

However, because this SDK supports different APIs, not just the Marketing API, and these APIs may not all follow the same conventions or may have different numbers and latest releases (in fact, for example, the Graph API version 14 is supported until 2024 while the Marketing API 14 will end support tomorrow), I'm wondering if this is really the case.

[Here](https://developers.facebook.com/docs/business-sdk/reference/versioning/) it's written

> The Meta Business SDK follows the same release cycle as the Graph API. New versions will be generated with a new release of the APIs. The SDK will have only one active version meaning we will not support bug fixes for older versions. Subversions of the active version are supported. For example, the active version is 3.0 but a bug was found; we will release the fix in the 3.0.1 subversion

However, it refers to the Graph API, not the Marketing API. So, I don't know if this applies to the Marketing API as well.

**Comment by stcheng** [comment]
Hi @nbro10. Thank you for bringing up this topic. You're right in your assumption that the SDK's major version aligns with the API version. It's important to note that while the [Marketing API](https://developers.facebook.com/docs/marketing-api/versions) is a subset of the Graph API, it has its own deprecation timeline which is much earlier. So, if you're using the SDK, it's natural to assume it follows the Graph API's release cycle. Yet, it's crucial to monitor the deprecation cycles of both the Marketing API and the Graph API individually.
