### ISSUE TITLE
Meta API does not respond to requests, hosted on Azure  

### ISSUE THREAD

**Issue by AlembicReid** [facebook/facebook-python-business-sdk#663]
Developer.facebook.com/support is broken

When we make a request via the facebook business api in python, such as 'create_campaign()', Intermittently the Azure APIM does not receive a response from our graph api, and eventually we time out. This error does not occur locally, only when deployed on azure.
 
Error placing ad for campaign: Meta: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by stcheng** [comment]
Based on the description, it appears to be more of an environment setup issue rather than an issue with the SDK or the Marketing API.

**Comment by AlembicReid** [comment]
Good morning Shuotian,

Looks like through our testing, we found that removing the SDK layer and making direct calls to the graph api fixed the issue. Please investigate this issue.

Thanks,
Reid



From: Shuotian Cheng ***@***.***>
Date: Friday, March 1, 2024 at 4:17 PM
To: facebook/facebook-python-business-sdk ***@***.***>
Cc: Reid Brostoff ***@***.***>, Author ***@***.***>
Subject: Re: [facebook/facebook-python-business-sdk] Meta API does not respond to requests, hosted on Azure (Issue #663)

Based on the description, it appears to be more of an environment setup issue rather than an issue with the SDK or the Marketing API.

**Comment by stcheng** [comment]
@AlembicReid Could you provide some more debugging details about this case? In your testing, how did you make the direct calls? Have you tried to construct the raw API calls within Python or via some CLIs?

**Comment by AlembicReid** [comment]
We opened a pr on dev in our azure env and replaced our ad preview functionality with the raw request to the graph api, this eliminated any errors we were seeing when deployed. Similar results for the create_campaign() function as well.

I have Cc’d the lead on this effort. Ammar Chaudhary.

From: Shuotian Cheng ***@***.***>
Date: Monday, March 4, 2024 at 3:15 PM
To: facebook/facebook-python-business-sdk ***@***.***>
Cc: Reid Brostoff ***@***.***>, Mention ***@***.***>
Subject: Re: [facebook/facebook-python-business-sdk] Meta API does not respond to requests, hosted on Azure (Issue #663)

@AlembicReid<https://github.com/AlembicReid> Could you provide some more debugging details about this case? In your testing, how did you make the direct calls? Have you tried to construct the raw API calls within Python or via some CLIs?
