### ISSUE TITLE
[BUG] Undefined symbol in __all__

### ISSUE THREAD

**Issue by ZuhairORZaki** [facebook/facebook-python-business-sdk#679]
# Reporting a bug found by iCR
**The bug detection tool created the following message:**

In file: [__init__.py](https://github.com/facebook/facebook-python-business-sdk/blob/20.0.0/facebook_business/__init__.py#L13), `__all__` includes an undefined symbol `objects`.

```diff
--- /workspace/source/facebook_business/__init__.py
+++ /workspace/source/facebook_business/__init__.py
@@ -8,8 +8,6 @@
 from facebook_business.api import FacebookAdsApi
 
 __version__ = '20.0.0'
-__all__ = [
-    'session',
-    'objects',
-    'api',
-]
+# Undefined names in "__all__": objects
+__all__ = ['session', 'api']
```
This will cause an `ImportError` when importing the module using star import i.e. `from facebook_business import *`. iCR suggests removing the undefined symbol if it is not needed.

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by stcheng** [comment]
thanks. resolved.

**Comment by potiuk** [comment]
Nice!

**Comment by potiuk** [comment]
FYI @stcheng -> this report was part of "Improving Apache Airflow supply chain security" project we run together wiht OpenRefactory and Alpha-Omega - and we might have more things coming from that. It's great to see one of the Airflow supply chain dependencies fixing security issues :)
