### ISSUE TITLE
EventRequestAsync Syntax Error

### ISSUE THREAD

**Issue by Modestzero** [facebook/facebook-python-business-sdk#683]
facebook_business/adobjects/serverside/event_request_async.py line 97
The word else is missing:
![image](https://github.com/user-attachments/assets/9da40f70-2fa8-4c63-b0d9-a9f2c4bd64d0)

**Comment by stcheng** [comment]
https://github.com/facebook/facebook-python-business-sdk/pull/682/ will resolve this issue.
